!function(v){function f(a){this.__index=null;this.__indexedRows=Object.create(null);this.__map=Object.create(null);this.__instance=null;this.__increment__();this._data=[];a instanceof Array&&this.load(a)}function g(a,b){if(!(a instanceof f)&&null!==a)throw Error("DataCollectionQuery requires valid DataCollection parent");if(!(b instanceof Array))throw Error("DataCollectionQuery requires valid Array of data");this.__parent=a;this.__parentInstance=a.__instance;this._data=b}f.prototype.__instances=0;
f.prototype.__increment__=function(){this.__parent||(this.__instance=this.constructor.prototype.__instances++)};f.prototype.__find__=function(a){var b=this._data,e=b.length;if(b[(e>>1)+1]===a)return(e>>1)+1;for(var c=0;c<e>>1;c++){if(b[c]===a)return c;if(b[e-c-1]===a)return e-c-1}return-1};f.prototype.__prepare__=function(a){var b=Array(a.length),e=0,c=[],d,k,t=this.__index,g=this.__indexedRows,h=this.__map,f=[],r;a.length&&"object"===typeof a[0]&&null!==a[0]&&(c=Object.keys(a[0]));k=c.length;f=Object.keys(this.__map);
r=f.length;if(t){p=0;for(u=a.length;p<u;p++)if((q=a[p])&&"object"===typeof q){n=g[q[t]]||(b[e++]=Object.create(null));for(l=0;l<k;l++)d=c[l],n[d]=q[d];for(l=0;l<r;l++)d=f[l],n[d]=h[d].call(this,n);g[n[t]]=n}b=b.slice(0,e)}else for(var p=0,u=a.length;p<u;p++){var q=a[p];if(q&&"object"===typeof q){for(var n=Object.create(null),l=0;l<k;l++)d=c[l],n[d]=q[d];for(l=0;l<r;l++)d=f[l],n[d]=h[d].call(this,n);b[p]=n}}return b};f.prototype.defineIndex=function(a){if(this.__parent)throw Error("Can only define indices on parent DataCollection");
this.__index=a;for(var b=Object.create(null),e=this._data,c=0,d=e.length;c<d;c++)b[e[c][a]]=e[c];this.__indexedRows=b;return this};f.prototype.createMapping=function(a,b){if(this.__parent)throw Error("Can only define maps on parent DataCollection");this.__map[a]=b;for(var e=this._data,c=0,d=e.length;c<d;c++){var k=e[c];k[a]=b.call(this,k)}return this};f.prototype.exists=function(a){return!!this.fetch(a)};f.prototype.fetch=function(a){if(null===this.__index)throw Error("No index defined on DataCollection");
return this.__indexedRows[a]||null};f.prototype.destroy=function(a){if(null===this.__index)throw Error("No index defined on DataCollection");var b=this.__indexedRows[a];if(!b)throw Error("Can not destroy, index does not exist");this._data.splice(this.__find__(b),1);delete this.__indexedRows[a];this.__increment__();return b};f.prototype.__remove__=function(a){var b=this._data,e=-1,c=this.__index,d={},k=Array(b.length-a);if(null===c)for(var g=0,f=b.length;g<f;g++)a=b[g],a.__remove__||(k[++e]=a);else{g=
0;for(f=b.length;g<f;g++)a=b[g],a.__remove__||(k[++e]=a,d[a[c]]=a);this.__indexedRows=d}this._data=k;this.__increment__();return!0};f.prototype.insert=function(a){a instanceof Array||(a=[].slice.call(arguments));this._data=this._data.concat(this.__prepare__(a));this.__increment__();return!0};f.prototype.load=function(a){a instanceof Array||(a=[].slice.call(arguments));this._data=this.__prepare__(a);this.__increment__();return!0};f.prototype.truncate=function(a){this.__indexedRows=Object.create(null);
this._data=[];return!0};f.prototype.query=function(){return new g(this,this._data.slice())};g.prototype.__validate__=function(){if(null!==this.__parent&&this.__parent.__instance!==this.__parentInstance)throw Error("Invalid DataCollection query, parent has been modified");};g.prototype.__compare={is:function(a,b){return a===b},not:function(a,b){return a!==b},gt:function(a,b){return a>b},lt:function(a,b){return a<b},gte:function(a,b){return a>=b},lte:function(a,b){return a<=b},icontains:function(a,
b){return-1<a.toLowerCase().indexOf(b.toLowerCase())},contains:function(a,b){return-1<a.indexOf(b)},"in":function(a,b){return-1<b.indexOf(a)},not_in:function(a,b){return-1===b.indexOf(a)}};g.prototype.__filter=function(a,b){this.__validate__();b=!!b;for(var e=this._data.slice(),c=Object.keys(a),d,k=[],f,m,h=0,s=c.length;h<s;h++){d=c[h];f=d.split("__");2>f.length&&f.push("is");m=f.pop();f=f.join("__");if(!this.__compare[m])throw Error('Filter type "'+m+'" not supported.');k.push([this.__compare[m],
f,a[d]])}var r;f=k.length;s=e.length;for(m=0;m!==f;m++)for(h=k[m],c=h[0],d=h[1],r=h[2],h=s;h--;)e[h]&&c(e[h][d],r)===b&&(e[h]=null);d=[];for(h=k=0;h!==s;h++)e[h]&&(d[k++]=e[h]);return new g(this.__parent,d)};g.prototype.filter=function(a){return this.__filter(a,!1)};g.prototype.exclude=function(a){return this.__filter(a,!0)};g.prototype.spawn=function(a){this.__validate__();var b=new f(this._data);if(a)return b;this.__parent.__index&&b.defineIndex(this.__parent.__index);return b};g.prototype.each=
function(a){if("function"!==typeof a)throw Error("DataCollectionQuery.each expects a callback");for(var b=this._data,e=0,c=b.length;e<c;e++)a.call(this,b[e],e);return this};g.prototype.update=function(a){this.__validate__();for(var b=Object.keys(a),e,c=b.length,d=0;d<c;d++)e=b[d],b[d]=[e,a[e]];a=this._data;for(var d=0,f=a.length;d<f;d++)for(var g=a[d],m=0;m<c;m++)e=b[m],g[e[0]]=e[1];return this};g.prototype.remove=function(){this.__validate__();this.update({__remove__:!0});return this.__parent.__remove__(this.count())};
g.prototype.sort=function(a,b){this.__validate__();a=(a+"").replace(/[^A-Za-z0-9]/gi,"_");var e=new Function("a","b",["var val = "+(b?-1:1)+";","if(a['"+a+"'] === b['"+a+"']) { return 0; }","if(a['"+a+"'] === null) { return -(val); }","if(b['"+a+"'] === null) { return (val); }","if(typeof a['"+a+"'] === 'number') {","  if(typeof b['"+a+"'] === 'number') {","    if(isNaN(a['"+a+"']) && isNaN(b['"+a+"'])) { return 0; }","    if(isNaN(b['"+a+"'])) { return (val); }","    return a['"+a+"'] > b['"+a+"'] ? (val) : -(val);",
"  }","  if(typeof b['"+a+"'] === 'boolean') { return -(val); }","  if(typeof b['"+a+"'] === 'string') { return -(val); }","  if(typeof b['"+a+"'] === 'object') { return -(val); }","}","if(typeof a['"+a+"'] === 'boolean') {","  if(typeof b['"+a+"'] === 'number') { return (val); }","  if(typeof b['"+a+"'] === 'boolean') { return a['"+a+"'] > b['"+a+"'] ? (val) : -(val); }","  if(typeof b['"+a+"'] === 'string') { return -(val); }","  if(typeof b['"+a+"'] === 'object') { return -(val); }","}","if(typeof a['"+
a+"'] === 'string') {","  if(typeof b['"+a+"'] === 'number') { return (val); }","  if(typeof b['"+a+"'] === 'boolean') { return (val); }","  if(typeof b['"+a+"'] === 'string') { return a['"+a+"'] > b['"+a+"'] ? (val) : -(val); }","  if(typeof b['"+a+"'] === 'object') { return -(val); }","}","if(typeof a['"+a+"'] === 'object') {","  if(typeof b['"+a+"'] === 'object') { return 0; }","  return (val);\n}\nreturn 0;"].join("\n")),e=this._data.slice().sort(e);return new g(this.__parent,e)};g.prototype.values=
function(a){this.__validate__();if(!a)return this._data.slice();for(var b=this._data,e=b.length,c=Array(e),d=0;d<e;d++)c[d]=b[d][a];return c};g.prototype.max=function(a){this.__validate__();var b=this._data,e=b.length,c=null,d;if(!e)return 0;for(var c=b[0][a],f=1;f<e;f++)d=b[f][a],d>c&&(c=d);return c};g.prototype.min=function(a){this.__validate__();var b=this._data,e=b.length,c=null,d;if(!e)return 0;for(var c=b[0][a],f=1;f<e;f++)d=b[f][a],d<c&&(c=d);return c};g.prototype.sum=function(a){this.__validate__();
var b=this._data,e=b.length,c;if(!e)return 0;c=parseFloat(b[0][a]);for(var d=1;d<e&&!isNaN(c);d++)c+=parseFloat(b[d][a]);return c};g.prototype.avg=function(a){this.__validate__();var b=this._data,e=b.length,c;if(!e)return 0;c=parseFloat(b[0][a]);for(var d=1;d<e&&!isNaN(c);d++)c+=parseFloat(b[d][a]);return c/e};g.prototype.reduce=function(a,b){this.__validate__();var e=this._data,c=e.length,d,f;if(!c)return null;f=e[0][a];for(var g=1;g<c;g++)d=e[g][a],f=b.call(this,f,d,g);return f};g.prototype.distinct=
function(a){this.__validate__();var b=this._data,e=b.length,c=Object.create(null),d;if(e){c[b[0][a]]=!0;for(var f=1;f<e;f++)d=b[f][a],c[d]||(c[d]=!0)}return Object.keys(c)};g.prototype.limit=function(a,b){this.__validate__();"undefined"===typeof b&&(b=a,a=0);return new g(this.__parent,this._data.slice(a,a+b))};g.prototype.count=function(){this.__validate__();return this._data.length};g.prototype.first=function(){return this._data.length?this._data[0]:null};g.prototype.last=function(){return this._data.length?
this._data[this._data.length-1]:null};v.DataCollection=f}(window);
