!function(x){function h(a){this.__instance=this.__index=null;this.__map=Object.create(null);this.load(a)}function g(a,b){this.__parent=a;this.__parentInstance=a.__instance;this._data=b}h.prototype.__instances=0;h.prototype.__increment__=function(){this.__instance=this.constructor.prototype.__instances++};h.prototype.__uniqid__=function(){return this.__uniqid++};h.prototype.__find__=function(a){var b=this._data,d=b.length;if(b[d>>>1]===a)return d>>>1;for(var c=0;c<d>>>1;c++){if(b[c]===a)return c;if(b[d-
c-1]===a)return d-c-1}return-1};h.prototype.__prepare__=function(a){var b=Array(a.length),d=0,c,e=[],f,k,m=this.__index,g=this.__indexedRows,h=this.__map,q=[],t;a.length&&"object"===typeof a[0]&&null!==a[0]&&Object.keys(a[0]);q=Object.keys(this.__map);t=q.length;if(m)for(n=0,s=a.length;n<s;n++){if((c=a[n])&&"object"===typeof c){p=g[c[m]]||(b[d++]=Object.defineProperty(Object.create(null),"__uniqid__",{value:this.__uniqid__()}));e=Object.keys(c);k=e.length;for(l=0;l<k;l++)f=e[l],p[f]=c[f];for(l=0;l<
t;l++)c=q[l],p[c]=h[c].call(this,p);g[p[m]]=p}}else for(var n=0,s=a.length;n<s;n++)if((c=a[n])&&"object"===typeof c){var p=Object.defineProperty(Object.create(null),"__uniqid__",{value:this.__uniqid__()}),e=Object.keys(c);k=e.length;for(var l=0;l<k;l++)f=e[l],p[f]=c[f];for(l=0;l<t;l++)c=q[l],p[c]=h[c].call(this,p);b[d++]=p}return b=b.slice(0,d)};h.prototype.defineIndex=function(a){if("string"!==typeof a)throw Error("Must have a valid string as an index parameter");this.__index=a+"";for(var b=Object.create(null),
d=this._data,c=0,e=d.length;c<e;c++)b[d[c][a]]=d[c];this.__indexedRows=b;return this};h.prototype.removeIndex=function(){this.__index=null;this.__indexedRows=Object.create(null)};h.prototype.createMapping=function(a,b){if("string"!==typeof a)throw Error("Must have a valid string as an key parameter for mapping");if("function"!==typeof b)throw Error("Mapping function must be a valid function");this.__map[a]=b;for(var d=this._data,c=0,e=d.length;c<e;c++){var f=d[c];f[a]=b.call(this,f)}return this};
h.prototype.exists=function(a){return!!this.fetch(a)};h.prototype.fetch=function(a){if(null===this.__index)throw Error("No index defined on DataCollection");return this.__indexedRows[a]||null};h.prototype.destroy=function(a){if(null===this.__index)throw Error("No index defined on DataCollection");var b=this.__indexedRows[a];if(!b)throw Error("Can not destroy, index does not exist");this.__find__(b);this._data.splice(this.__find__(b),1);delete this.__indexedRows[a];this.__increment__();return b};h.prototype.__remove__=
function(a){var b=this._data,d=-1,c=this.__index,e={},f=Array(b.length-a);if(null===c)for(var k=0,m=b.length;k<m;k++)a=b[k],a.__remove__||(f[++d]=a);else{k=0;for(m=b.length;k<m;k++)a=b[k],a.__remove__||(f[++d]=a,e[a[c]]=a);this.__indexedRows=e}this._data=f;this.__increment__();return!0};h.prototype.insert=function(a){a instanceof Array||(a=[].slice.call(arguments));this._data=this._data.concat(this.__prepare__(a));this.__increment__();return!0};h.prototype.load=function(a){a instanceof Array||(a=
[].slice.call(arguments));this.__indexedRows=Object.create(null);this.__uniqid=0;this._data=this.__prepare__(a);this.__increment__();return!0};h.prototype.truncate=function(a){this.__indexedRows=Object.create(null);this.__uniqid=0;this._data=[];this.__increment__();return!0};h.prototype.query=function(){return new g(this,this._data.slice())};g.prototype.__validate__=function(){if(null!==this.__parent&&this.__parent.__instance!==this.__parentInstance)throw Error("Invalid DataCollection query, parent has been modified");
};g.prototype.__compare={is:function(a,b){return a===b},not:function(a,b){return a!==b},gt:function(a,b){return a>b},lt:function(a,b){return a<b},gte:function(a,b){return a>=b},lte:function(a,b){return a<=b},icontains:function(a,b){return-1<a.toLowerCase().indexOf(b.toLowerCase())},contains:function(a,b){return-1<a.indexOf(b)},"in":function(a,b){return-1<b.indexOf(a)},not_in:function(a,b){return-1===b.indexOf(a)}};g.prototype.__filter=function(a,b){this.__validate__();b=!!b;for(var d=0,c=a.length;d<
c;d++)if("object"!==typeof a[d]||null===a[d])a[d]={};a.length||(a=[{}]);var e=this._data.slice(),f,k,m,h,r,q,t=a.length,n,s,p;for(n=0;n!==t;n++){f=a[n];k=Object.keys(f);h=[];d=0;for(c=k.length;d<c;d++){m=k[d];r=m.split("__");2>r.length&&r.push("is");q=r.pop();if(!this.__compare[q])throw Error('Filter type "'+q+'" not supported.');h.push([this.__compare[q],r,f[m]])}a[n]=h}var l,y,z,w,A,c=e.length,u;f=0;k=Array(c);r=0;var v;try{for(d=0;d!==c;d++)for(w=e[d],u=!0,s=0;s!==t&&u;s++){u=!1;h=a[s];A=h.length;
for(p=0;p!==A&&!u;p++){l=h[p];y=l[0];v=w;m=l[1];n=0;for(r=m.length;n!==r;n++)v=v[m[n]];z=l[2];y(v,z)===b&&(u=!0)}!u&&(k[f++]=w)}}catch(x){throw Error("Nested field "+m.join("__")+" does not exist");}k=k.slice(0,f);return new g(this.__parent,k)};g.prototype.filter=function(a){var b=[].slice.call(arguments);return this.__filter(b,!1)};g.prototype.exclude=function(a){var b=[].slice.call(arguments);return this.__filter(b,!0)};g.prototype.spawn=function(a){this.__validate__();var b=new h(this._data);if(a)return b;
this.__parent.__index&&b.defineIndex(this.__parent.__index);return b};g.prototype.each=function(a){if("function"!==typeof a)throw Error("DataCollectionQuery.each expects a callback");for(var b=this._data,d=0,c=b.length;d<c;d++)a.call(this,b[d],d);return this};g.prototype.update=function(a){this.__validate__();for(var b=Object.keys(a),d,c=b.length,e=0;e<c;e++)d=b[e],b[e]=[d,a[d]];a=this._data;for(var e=0,f=a.length;e<f;e++)for(var k=a[e],m=0;m<c;m++)d=b[m],k[d[0]]=d[1];return this};g.prototype.remove=
function(){this.__validate__();this.update({__remove__:!0});return this.__parent.__remove__(this.count())};g.prototype.order=function(a,b){this.__validate__();var d=a=(a+"").replace(/[^A-Za-z0-9-_]/gi,"?");a="['"+a.split("__").join("']['")+"']";var c=new Function("a","b",["var val = "+(b?-1:1)+";","if(a"+a+" === b"+a+") { return a.__uniqid__ > b.__uniqid__ ? (val) : -(val); }","if(a"+a+" === undefined) { return 1; }","if(b"+a+" === undefined) { return -1; }","if(a"+a+" === null) { return 1; }","if(b"+
a+" === null) { return -1; }","if(typeof a"+a+" === 'function') {","  if(typeof b"+a+" === 'function') { return a.__uniqid__ > b.__uniqid__ ? (val) : -(val); }","  return -1;\n}","if(typeof a"+a+" === 'object') {","  if(typeof b"+a+" === 'function') { return 1; }","  if(typeof b"+a+" === 'object') {","    if(a"+a+" instanceof Date && b"+a+" instanceof Date) {","        return a"+a+".valueOf() > b"+a+".valueOf() ? (val) : -(val);","    }","    if(a"+a+" instanceof Date) { return 1; }","    if(b"+a+
" instanceof Date) { return -1; }","    return a.__uniqid__ > b.__uniqid__ ? (val) : -(val);\n  }\n  return -1;\n}","if(typeof a"+a+" === 'string') {","  if(typeof b"+a+" === 'function') { return 1; }","  if(typeof b"+a+" === 'object') { return 1; }","  if(typeof b"+a+" === 'string') { return a"+a+" > b"+a+" ? (val) : -(val); }","  return -1;\n}","if(typeof a"+a+" === 'boolean') {","  if(typeof b"+a+" === 'boolean') { return a"+a+" > b"+a+" ? (val) : -(val); }","  if(typeof b"+a+" === 'number') { return -1; }",
"  return 1;\n}","if(typeof a"+a+" === 'number') {","  if(typeof b"+a+" === 'number') {","    if(isNaN(a"+a+") && isNaN(b"+a+")) { return a.__uniqid__ > b.__uniqid__ ? (val) : -(val); }","    if(isNaN(a"+a+")) { return 1; }","    if(isNaN(b"+a+")) { return -1; }","    return a"+a+" > b"+a+" ? (val) : -(val);","  }\n  return 1;\n}\nreturn a.__uniqid__ > b.__uniqid__ ? (val) : -(val);"].join("\n"));try{var e=this._data.slice().sort(c)}catch(f){throw Error("Key "+d+" could not be sorted by");}return new g(this.__parent,
e)};g.prototype.sort=g.prototype.order;g.prototype.values=function(a){this.__validate__();if(!a)return this._data.slice();for(var b=this._data,d=b.length,c=Array(d),e=0;e<d;e++)c[e]=b[e][a];return c};g.prototype.max=function(a){this.__validate__();var b=this._data,d=b.length,c=null,e;if(!d)return 0;for(var c=b[0][a],f=1;f<d;f++)e=b[f][a],e>c&&(c=e);return c};g.prototype.min=function(a){this.__validate__();var b=this._data,d=b.length,c=null,e;if(!d)return 0;for(var c=b[0][a],f=1;f<d;f++)e=b[f][a],
e<c&&(c=e);return c};g.prototype.sum=function(a){this.__validate__();var b=this._data,d=b.length,c;if(!d)return 0;c=parseFloat(b[0][a]);for(var e=1;e<d&&!isNaN(c);e++)c+=parseFloat(b[e][a]);return c};g.prototype.avg=function(a){this.__validate__();var b=this._data,d=b.length,c;if(!d)return 0;c=parseFloat(b[0][a]);for(var e=1;e<d&&!isNaN(c);e++)c+=parseFloat(b[e][a]);return c/d};g.prototype.reduce=function(a,b){this.__validate__();var d=this._data,c=d.length,e,f;if(!c)return null;f=d[0][a];for(var k=
1;k<c;k++)e=d[k][a],f=b.call(this,f,e,k);return f};g.prototype.distinct=function(a){this.__validate__();var b=this._data,d=b.length,c=Object.create(null),e;if(d){c[b[0][a]+"__"+typeof b[0][a]]=!0;for(var f=1;f<d;f++)e=b[f][a]+"__"+typeof b[f][a],c[e]||(c[e]=!0)}a=Object.keys(c);e={undefined:function(a){},number:function(a){return Number(a)},string:function(a){return a},"boolean":function(a){return{"true":!0,"false":!1}[a]},object:function(a){return"null"===a?null:Object.create(null)},"function":function(a){return function(){}}};
f=0;for(d=a.length;f<d;f++)b=a[f].split("__"),c=b.pop(),a[f]=e[c](b.join("__"));return a.sort(function(a,b){return a===b?0:void 0===a?1:void 0===b?-1:null===a?1:null===b?-1:"function"===typeof a?"function"===typeof b?0:-1:"object"===typeof a?"function"===typeof b?1:"object"===typeof b?0:-1:"string"===typeof a?"function"===typeof b||"object"===typeof b?1:"string"===typeof b?a>b?1:-1:-1:"boolean"===typeof a?"boolean"===typeof b?a>b?1:-1:"number"===typeof b?-1:1:"number"===typeof b?isNaN(a)&&isNaN(b)?
0:isNaN(a)?1:isNaN(b)?-1:a>b?1:-1:1})};g.prototype.sequence=function(a){this.__validate__();var b=this.__parent;if(!b.__index)throw Error("Can only use .sequence with an indexed DataCollection");a instanceof Array||(a=[].slice.call(arguments));for(var d=[],c=b.__indexedRows,e=0,f=a.length;e<f;e++)b=a[e],c[b]&&d.push(c[b]);return new g(this.__parent,d)};g.prototype.limit=function(a,b){this.__validate__();"undefined"===typeof b&&(b=a,a=0);return new g(this.__parent,this._data.slice(a,a+b))};g.prototype.count=
function(){this.__validate__();return this._data.length};g.prototype.first=function(){return this._data.length?this._data[0]:null};g.prototype.last=function(){return this._data.length?this._data[this._data.length-1]:null};x.DataCollection=h}(window);
