!function(w){function g(a){this.__instance=this.__index=null;this.__map=Object.create(null);this.load(a)}function f(a,b){this.__parent=a;this.__parentInstance=a.__instance;this._data=b}g.prototype.__instances=0;g.prototype.__increment__=function(){this.__instance=this.constructor.prototype.__instances++};g.prototype.__uniqid__=function(){return this.__uniqid++};g.prototype.__find__=function(a){var b=this._data,c=b.length;if(b[c>>>1]===a)return c>>>1;for(var d=0;d<c>>>1;d++){if(b[d]===a)return d;if(b[c-
d-1]===a)return c-d-1}return-1};g.prototype.__prepare__=function(a){var b=Array(a.length),c=0,d=[],e,h,v=this.__index,f=this.__indexedRows,g=this.__map,m=[],p;a.length&&"object"===typeof a[0]&&null!==a[0]&&(d=Object.keys(a[0]));h=d.length;m=Object.keys(this.__map);p=m.length;if(v){q=0;for(r=a.length;q<r;q++)if((n=a[q])&&"object"===typeof n){l=f[n[v]]||(b[c++]=Object.defineProperty(Object.create(null),"__uniqid__",{value:this.__uniqid__()}));for(k=0;k<h;k++)e=d[k],l[e]=n[e];for(k=0;k<p;k++)e=m[k],
l[e]=g[e].call(this,l);f[l[v]]=l}b=b.slice(0,c)}else for(var q=0,r=a.length;q<r;q++){var n=a[q];if(n&&"object"===typeof n){for(var l=Object.defineProperty(Object.create(null),"__uniqid__",{value:this.__uniqid__()}),k=0;k<h;k++)e=d[k],l[e]=n[e];for(k=0;k<p;k++)e=m[k],l[e]=g[e].call(this,l);b[q]=l}}return b};g.prototype.defineIndex=function(a){if("string"!==typeof a)throw Error("Must have a valid string as an index parameter");this.__index=a+"";for(var b=Object.create(null),c=this._data,d=0,e=c.length;d<
e;d++)b[c[d][a]]=c[d];this.__indexedRows=b;return this};g.prototype.createMapping=function(a,b){if("string"!==typeof a)throw Error("Must have a valid string as an key parameter for mapping");if("function"!==typeof b)throw Error("Mapping function must be a valid function");this.__map[a]=b;for(var c=this._data,d=0,e=c.length;d<e;d++){var h=c[d];h[a]=b.call(this,h)}return this};g.prototype.exists=function(a){return!!this.fetch(a)};g.prototype.fetch=function(a){if(null===this.__index)throw Error("No index defined on DataCollection");
return this.__indexedRows[a]||null};g.prototype.destroy=function(a){if(null===this.__index)throw Error("No index defined on DataCollection");var b=this.__indexedRows[a];if(!b)throw Error("Can not destroy, index does not exist");this.__find__(b);this._data.splice(this.__find__(b),1);delete this.__indexedRows[a];this.__increment__();return b};g.prototype.__remove__=function(a){var b=this._data,c=-1,d=this.__index,e={},h=Array(b.length-a);if(null===d)for(var f=0,g=b.length;f<g;f++)a=b[f],a.__remove__||
(h[++c]=a);else{f=0;for(g=b.length;f<g;f++)a=b[f],a.__remove__||(h[++c]=a,e[a[d]]=a);this.__indexedRows=e}this._data=h;this.__increment__();return!0};g.prototype.insert=function(a){a instanceof Array||(a=[].slice.call(arguments));this._data=this._data.concat(this.__prepare__(a));this.__increment__();return!0};g.prototype.load=function(a){a instanceof Array||(a=[].slice.call(arguments));this.__indexedRows=Object.create(null);this.__uniqid=0;this._data=this.__prepare__(a);this.__increment__();return!0};
g.prototype.truncate=function(a){this.__indexedRows=Object.create(null);this._data=[];return!0};g.prototype.query=function(){return new f(this,this._data.slice())};f.prototype.__validate__=function(){if(null!==this.__parent&&this.__parent.__instance!==this.__parentInstance)throw Error("Invalid DataCollection query, parent has been modified");};f.prototype.__compare={is:function(a,b){return a===b},not:function(a,b){return a!==b},gt:function(a,b){return a>b},lt:function(a,b){return a<b},gte:function(a,
b){return a>=b},lte:function(a,b){return a<=b},icontains:function(a,b){return-1<a.toLowerCase().indexOf(b.toLowerCase())},contains:function(a,b){return-1<a.indexOf(b)},"in":function(a,b){return-1<b.indexOf(a)},not_in:function(a,b){return-1===b.indexOf(a)}};f.prototype.__filter=function(a,b){this.__validate__();b=!!b;for(var c=0,d=a.length;c<d;c++)if("object"!==typeof a[c]||null===a[c])a[c]={};a.length||(a=[{}]);var e=this._data.slice(),h,g,t,s,m,p,q=a.length,r;for(r=0;r!==q;r++){h=a[r];g=Object.keys(h);
s=[];c=0;for(d=g.length;c<d;c++){t=g[c];m=t.split("__");2>m.length&&m.push("is");p=m.pop();m=m.join("__");if(!this.__compare[p])throw Error('Filter type "'+p+'" not supported.');s.push([this.__compare[p],m,h[t]])}a[r]=s}for(var n,d=e.length,l,k=0,u=Array(d),c=0;c!==d;c++)for(p=e[c],l=!0,h=0;h!==q&&l;h++){l=!1;s=a[h];r=s.length;for(g=0;g!==r&&!l;g++)n=s[g],m=n[0],t=n[1],n=n[2],m(p[t],n)===b&&(l=!0);!l&&(u[k++]=p)}u=u.slice(0,k);return new f(this.__parent,u)};f.prototype.filter=function(a){var b=[].slice.call(arguments);
return this.__filter(b,!1)};f.prototype.exclude=function(a){var b=[].slice.call(arguments);return this.__filter(b,!0)};f.prototype.spawn=function(a){this.__validate__();var b=new g(this._data);if(a)return b;this.__parent.__index&&b.defineIndex(this.__parent.__index);return b};f.prototype.each=function(a){if("function"!==typeof a)throw Error("DataCollectionQuery.each expects a callback");for(var b=this._data,c=0,d=b.length;c<d;c++)a.call(this,b[c],c);return this};f.prototype.update=function(a){this.__validate__();
for(var b=Object.keys(a),c,d=b.length,e=0;e<d;e++)c=b[e],b[e]=[c,a[c]];a=this._data;for(var e=0,h=a.length;e<h;e++)for(var f=a[e],g=0;g<d;g++)c=b[g],f[c[0]]=c[1];return this};f.prototype.remove=function(){this.__validate__();this.update({__remove__:!0});return this.__parent.__remove__(this.count())};f.prototype.sort=function(a,b){this.__validate__();a=(a+"").replace(/[^A-Za-z0-9]/gi,"_");var c=new Function("a","b",["var val = "+(b?-1:1)+";","if(a['"+a+"'] === b['"+a+"']) { return 0; }","if(a['"+a+
"'] === null) { return -(val); }","if(b['"+a+"'] === null) { return (val); }","if(typeof a['"+a+"'] === 'number') {","  if(typeof b['"+a+"'] === 'number') {","    if(isNaN(a['"+a+"']) && isNaN(b['"+a+"'])) { return 0; }","    if(isNaN(b['"+a+"'])) { return (val); }","    return a['"+a+"'] > b['"+a+"'] ? (val) : -(val);","  }","  if(typeof b['"+a+"'] === 'boolean') { return -(val); }","  if(typeof b['"+a+"'] === 'string') { return -(val); }","  if(typeof b['"+a+"'] === 'object') { return -(val); }",
"}","if(typeof a['"+a+"'] === 'boolean') {","  if(typeof b['"+a+"'] === 'number') { return (val); }","  if(typeof b['"+a+"'] === 'boolean') { return a['"+a+"'] > b['"+a+"'] ? (val) : -(val); }","  if(typeof b['"+a+"'] === 'string') { return -(val); }","  if(typeof b['"+a+"'] === 'object') { return -(val); }","}","if(typeof a['"+a+"'] === 'string') {","  if(typeof b['"+a+"'] === 'number') { return (val); }","  if(typeof b['"+a+"'] === 'boolean') { return (val); }","  if(typeof b['"+a+"'] === 'string') { return a['"+
a+"'] > b['"+a+"'] ? (val) : -(val); }","  if(typeof b['"+a+"'] === 'object') { return -(val); }","}","if(typeof a['"+a+"'] === 'object') {","  if(typeof b['"+a+"'] === 'object') { return 0; }","  return (val);\n}\nreturn 0;"].join("\n")),c=this._data.slice().sort(c);return new f(this.__parent,c)};f.prototype.values=function(a){this.__validate__();if(!a)return this._data.slice();for(var b=this._data,c=b.length,d=Array(c),e=0;e<c;e++)d[e]=b[e][a];return d};f.prototype.max=function(a){this.__validate__();
var b=this._data,c=b.length,d=null,e;if(!c)return 0;for(var d=b[0][a],f=1;f<c;f++)e=b[f][a],e>d&&(d=e);return d};f.prototype.min=function(a){this.__validate__();var b=this._data,c=b.length,d=null,e;if(!c)return 0;for(var d=b[0][a],f=1;f<c;f++)e=b[f][a],e<d&&(d=e);return d};f.prototype.sum=function(a){this.__validate__();var b=this._data,c=b.length,d;if(!c)return 0;d=parseFloat(b[0][a]);for(var e=1;e<c&&!isNaN(d);e++)d+=parseFloat(b[e][a]);return d};f.prototype.avg=function(a){this.__validate__();
var b=this._data,c=b.length,d;if(!c)return 0;d=parseFloat(b[0][a]);for(var e=1;e<c&&!isNaN(d);e++)d+=parseFloat(b[e][a]);return d/c};f.prototype.reduce=function(a,b){this.__validate__();var c=this._data,d=c.length,e,f;if(!d)return null;f=c[0][a];for(var g=1;g<d;g++)e=c[g][a],f=b.call(this,f,e,g);return f};f.prototype.distinct=function(a){this.__validate__();var b=this._data,c=b.length,d=Object.create(null),e;if(c){d[b[0][a]]=!0;for(var f=1;f<c;f++)e=b[f][a],d[e]||(d[e]=!0)}return Object.keys(d)};
f.prototype.limit=function(a,b){this.__validate__();"undefined"===typeof b&&(b=a,a=0);return new f(this.__parent,this._data.slice(a,a+b))};f.prototype.count=function(){this.__validate__();return this._data.length};f.prototype.first=function(){return this._data.length?this._data[0]:null};f.prototype.last=function(){return this._data.length?this._data[this._data.length-1]:null};w.DataCollection=g}(window);
