!function(t){function g(a){this.__index=null;this.__indexedRows=Object.create(null);this.__map=Object.create(null);this.__instance=null;this.__increment__();this._data=[];a instanceof Array&&this.load(a)}function f(a,b){if(!(a instanceof g)&&null!==a)throw Error("DataCollectionQuery requires valid DataCollection parent");if(!(b instanceof Array))throw Error("DataCollectionQuery requires valid Array of data");this.__parent=a;this.__parentInstance=a.__instance;this._data=b}g.prototype.__instances=0;
g.prototype.__increment__=function(){this.__parent||(this.__instance=this.constructor.prototype.__instances++)};g.prototype.__find__=function(a){var b=this._data,d=b.length;if(b[(d>>1)+1]===a)return(d>>1)+1;for(var c=0;c<d>>1;c++){if(b[c]===a)return c;if(b[d-c-1]===a)return d-c-1}return-1};g.prototype.__prepare__=function(a){var b=Array(a.length),d=[],c,e,k=this.__index,u=this.__indexedRows,f=this.__map,h=[],g;a.length&&"object"===typeof a[0]&&null!==a[0]&&(d=Object.keys(a[0]));e=d.length;h=Object.keys(this.__map);
g=h.length;if(k)for(n=0,s=a.length;n<s;n++){if((q=a[n])&&"object"===typeof q){p=Object.create(null);for(l=0;l<e;l++)c=d[l],p[c]=q[c];for(l=0;l<g;l++)c=h[l],p[c]=f[c].call(this,p);u[p[k]]=p;b[n]=p}}else for(var n=0,s=a.length;n<s;n++){var q=a[n];if(q&&"object"===typeof q){for(var p=Object.create(null),l=0;l<e;l++)c=d[l],p[c]=q[c];for(l=0;l<g;l++)c=h[l],p[c]=f[c].call(this,p);b[n]=p}}return b};g.prototype.defineIndex=function(a){if(this.__parent)throw Error("Can only define indices on parent DataCollection");
this.__index=a;for(var b=Object.create(null),d=this._data,c=0,e=d.length;c<e;c++)b[d[c][a]]=d[c];this.__indexedRows=b;return this};g.prototype.createMapping=function(a,b){if(this.__parent)throw Error("Can only define maps on parent DataCollection");this.__map[a]=b;for(var d=this._data,c=0,e=d.length;c<e;c++){var k=d[c];k[a]=b.call(this,k)}return this};g.prototype.exists=function(a){return!!this.fetch(a)};g.prototype.fetch=function(a){if(null===this.__index)throw Error("No index defined on DataCollection");
return this.__indexedRows[a]||null};g.prototype.destroy=function(a){if(null===this.__index)throw Error("No index defined on DataCollection");var b=this.__indexedRows[a];if(!b)throw Error("Can not destroy, index does not exist");this._data.splice(this.__find__(b),1);delete this.__indexedRows[a];this.__increment__();return b};g.prototype.__remove__=function(a){var b=this._data,d=-1,c=this.__index,e={},k=Array(b.length-a);if(null===c)for(var f=0,g=b.length;f<g;f++)a=b[f],a.__remove__||(k[++d]=a);else{f=
0;for(g=b.length;f<g;f++)a=b[f],a.__remove__||(k[++d]=a,e[a[c]]=a);this.__indexedRows=e}this._data=k;this.__increment__();return!0};g.prototype.insert=function(a){a instanceof Array||(a=[].slice.call(arguments));this._data=this._data.concat(this.__prepare__(a));this.__increment__();return!0};g.prototype.load=function(a){a instanceof Array||(a=[].slice.call(arguments));this._data=this.__prepare__(a);this.__increment__();return!0};g.prototype.truncate=function(a){this.__indexedRows=Object.create(null);
this._data=[];return!0};g.prototype.query=function(){return new f(this,this._data.slice())};f.prototype.__validate__=function(){if(null!==this.__parent&&this.__parent.__instance!==this.__parentInstance)throw Error("Invalid DataCollection query, parent has been modified");};f.prototype.__compare={is:function(a,b){return a===b},not:function(a,b){return a!==b},gt:function(a,b){return a>b},lt:function(a,b){return a<b},gte:function(a,b){return a>=b},lte:function(a,b){return a<=b},icontains:function(a,
b){return-1<a.toLowerCase().indexOf(b.toLowerCase())},contains:function(a,b){return-1<a.indexOf(b)},"in":function(a,b){return-1<b.indexOf(a)},not_in:function(a,b){return-1===b.indexOf(a)}};f.prototype.__filter=function(a,b){this.__validate__();b=!!b;for(var d=this._data.slice(),c=Object.keys(a),e,k=[],g,m,h=0,r=c.length;h<r;h++){e=c[h];g=e.split("__");2>g.length&&g.push("is");m=g.pop();g=g.join("__");if(!this.__compare[m])throw Error('Filter type "'+m+'" not supported.');k.push([this.__compare[m],
g,a[e]])}var n;g=k.length;r=d.length;for(m=0;m!==g;m++)for(h=k[m],c=h[0],e=h[1],n=h[2],h=r;h--;)d[h]&&c(d[h][e],n)===b&&(d[h]=null);e=[];for(h=k=0;h!==r;h++)d[h]&&(e[k++]=d[h]);return new f(this.__parent,e)};f.prototype.filter=function(a){return this.__filter(a,!1)};f.prototype.exclude=function(a){return this.__filter(a,!0)};f.prototype.spawn=function(a){this.__validate__();var b=new g(this._data);if(a)return b;this.__parent.__index&&b.defineIndex(this.__parent.__index);return b};f.prototype.each=
function(a){if("function"!==typeof a)throw Error("DataCollectionQuery.each expects a callback");for(var b=this._data,d=0,c=b.length;d<c;d++)a.call(this,b[d],d);return this};f.prototype.update=function(a){this.__validate__();for(var b=Object.keys(a),d,c=b.length,e=0;e<c;e++)d=b[e],b[e]=[d,a[d]];a=this._data;for(var e=0,f=a.length;e<f;e++)for(var g=a[e],m=0;m<c;m++)d=b[m],g[d[0]]=d[1];return this};f.prototype.remove=function(){this.__validate__();this.update({__remove__:!0});return this.__parent.__remove__(this.count())};
f.prototype.sort=function(a,b){this.__validate__();a=(a+"").replace(/[^A-Za-z0-9]/gi,"_");var d=new Function("a","b",["var val = "+(b?-1:1)+";","if(a['"+a+"'] === b['"+a+"']) { return 0; }","if(a['"+a+"'] === null) { return -(val); }","if(b['"+a+"'] === null) { return (val); }","if(typeof a['"+a+"'] === 'number') {","  if(typeof b['"+a+"'] === 'number') {","    if(isNaN(a['"+a+"']) && isNaN(b['"+a+"'])) { return 0; }","    if(isNaN(b['"+a+"'])) { return (val); }","    return a['"+a+"'] > b['"+a+"'] ? (val) : -(val);",
"  }","  if(typeof b['"+a+"'] === 'boolean') { return -(val); }","  if(typeof b['"+a+"'] === 'string') { return -(val); }","  if(typeof b['"+a+"'] === 'object') { return -(val); }","}","if(typeof a['"+a+"'] === 'boolean') {","  if(typeof b['"+a+"'] === 'number') { return (val); }","  if(typeof b['"+a+"'] === 'boolean') { return a['"+a+"'] > b['"+a+"'] ? (val) : -(val); }","  if(typeof b['"+a+"'] === 'string') { return -(val); }","  if(typeof b['"+a+"'] === 'object') { return -(val); }","}","if(typeof a['"+
a+"'] === 'string') {","  if(typeof b['"+a+"'] === 'number') { return (val); }","  if(typeof b['"+a+"'] === 'boolean') { return (val); }","  if(typeof b['"+a+"'] === 'string') { return a['"+a+"'] > b['"+a+"'] ? (val) : -(val); }","  if(typeof b['"+a+"'] === 'object') { return -(val); }","}","if(typeof a['"+a+"'] === 'object') {","  if(typeof b['"+a+"'] === 'object') { return 0; }","  return (val);\n}\nreturn 0;"].join("\n")),d=this._data.slice().sort(d);return new f(this.__parent,d)};f.prototype.values=
function(a){this.__validate__();if(!a)return this._data.slice();for(var b=this._data,d=b.length,c=Array(d),e=0;e<d;e++)c[e]=b[e][a];return c};f.prototype.max=function(a){this.__validate__();var b=this._data,d=b.length,c=null,e;if(!d)return 0;for(var c=b[0][a],f=1;f<d;f++)e=b[f][a],e>c&&(c=e);return c};f.prototype.min=function(a){this.__validate__();var b=this._data,d=b.length,c=null,e;if(!d)return 0;for(var c=b[0][a],f=1;f<d;f++)e=b[f][a],e<c&&(c=e);return c};f.prototype.sum=function(a){this.__validate__();
var b=this._data,d=b.length,c;if(!d)return 0;c=parseFloat(b[0][a]);for(var e=1;e<d&&!isNaN(c);e++)c+=parseFloat(b[e][a]);return c};f.prototype.avg=function(a){this.__validate__();var b=this._data,d=b.length,c;if(!d)return 0;c=parseFloat(b[0][a]);for(var e=1;e<d&&!isNaN(c);e++)c+=parseFloat(b[e][a]);return c/d};f.prototype.reduce=function(a,b){this.__validate__();var d=this._data,c=d.length,e,f;if(!c)return null;f=d[0][a];for(var g=1;g<c;g++)e=d[g][a],f=b.call(this,f,e,g);return f};f.prototype.distinct=
function(a){this.__validate__();var b=this._data,d=b.length,c=Object.create(null),e;if(d){c[b[0][a]]=!0;for(var f=1;f<d;f++)e=b[f][a],c[e]||(c[e]=!0)}return Object.keys(c)};f.prototype.limit=function(a,b){this.__validate__();"undefined"===typeof b&&(b=a,a=0);return new f(this.__parent,this._data.slice(a,a+b))};f.prototype.count=function(){this.__validate__();return this._data.length};f.prototype.first=function(){return this._data.length?this._data[0]:null};f.prototype.last=function(){return this._data.length?
this._data[this._data.length-1]:null};t.DataCollection=g}(window);
