!function(v){function g(a){this.__instance=this.__index=null;this.__map=Object.create(null);this.load(a)}function e(a,b){this.__parent=a;this.__parentInstance=a.__instance;this._data=b}g.prototype.__instances=0;g.prototype.__increment__=function(){this.__instance=this.constructor.prototype.__instances++};g.prototype.__uniqid__=function(){return this.__uniqid++};g.prototype.__find__=function(a){var b=this._data,d=b.length;if(b[d>>>1]===a)return d>>>1;for(var c=0;c<d>>>1;c++){if(b[c]===a)return c;if(b[d-
c-1]===a)return d-c-1}return-1};g.prototype.__prepare__=function(a){var b=Array(a.length),d=0,c,f=[],h,e,g=this.__index,r=this.__indexedRows,n=this.__map,p=[],s;a.length&&"object"===typeof a[0]&&null!==a[0]&&Object.keys(a[0]);p=Object.keys(this.__map);s=p.length;if(g)for(m=0,q=a.length;m<q;m++){if((c=a[m])&&"object"===typeof c){l=r[c[g]]||(b[d++]=Object.defineProperty(Object.create(null),"__uniqid__",{value:this.__uniqid__()}));f=Object.keys(c);e=f.length;for(k=0;k<e;k++)h=f[k],l[h]=c[h];for(k=0;k<
s;k++)c=p[k],l[c]=n[c].call(this,l);r[l[g]]=l}}else for(var m=0,q=a.length;m<q;m++)if((c=a[m])&&"object"===typeof c){var l=Object.defineProperty(Object.create(null),"__uniqid__",{value:this.__uniqid__()}),f=Object.keys(c);e=f.length;for(var k=0;k<e;k++)h=f[k],l[h]=c[h];for(k=0;k<s;k++)c=p[k],l[c]=n[c].call(this,l);b[d++]=l}return b=b.slice(0,d)};g.prototype.defineIndex=function(a){if("string"!==typeof a)throw Error("Must have a valid string as an index parameter");this.__index=a+"";for(var b=Object.create(null),
d=this._data,c=0,f=d.length;c<f;c++)b[d[c][a]]=d[c];this.__indexedRows=b;return this};g.prototype.removeIndex=function(){this.__index=null;this.__indexedRows=Object.create(null)};g.prototype.createMapping=function(a,b){if("string"!==typeof a)throw Error("Must have a valid string as an key parameter for mapping");if("function"!==typeof b)throw Error("Mapping function must be a valid function");this.__map[a]=b;for(var d=this._data,c=0,f=d.length;c<f;c++){var h=d[c];h[a]=b.call(this,h)}return this};
g.prototype.exists=function(a){return!!this.fetch(a)};g.prototype.fetch=function(a){if(null===this.__index)throw Error("No index defined on DataCollection");return this.__indexedRows[a]||null};g.prototype.destroy=function(a){if(null===this.__index)throw Error("No index defined on DataCollection");var b=this.__indexedRows[a];if(!b)throw Error("Can not destroy, index does not exist");this.__find__(b);this._data.splice(this.__find__(b),1);delete this.__indexedRows[a];this.__increment__();return b};g.prototype.__remove__=
function(a){var b=this._data,d=-1,c=this.__index,f={},h=Array(b.length-a);if(null===c)for(var e=0,g=b.length;e<g;e++)a=b[e],a.__remove__||(h[++d]=a);else{e=0;for(g=b.length;e<g;e++)a=b[e],a.__remove__||(h[++d]=a,f[a[c]]=a);this.__indexedRows=f}this._data=h;this.__increment__();return!0};g.prototype.insert=function(a){a instanceof Array||(a=[].slice.call(arguments));this._data=this._data.concat(this.__prepare__(a));this.__increment__();return!0};g.prototype.load=function(a){a instanceof Array||(a=
[].slice.call(arguments));this.__indexedRows=Object.create(null);this.__uniqid=0;this._data=this.__prepare__(a);this.__increment__();return!0};g.prototype.truncate=function(a){this.__indexedRows=Object.create(null);this.__uniqid=0;this._data=[];this.__increment__();return!0};g.prototype.query=function(){return new e(this,this._data.slice())};e.prototype.__validate__=function(){if(null!==this.__parent&&this.__parent.__instance!==this.__parentInstance)throw Error("Invalid DataCollection query, parent has been modified");
};e.prototype.__compare={is:function(a,b){return a===b},not:function(a,b){return a!==b},gt:function(a,b){return a>b},lt:function(a,b){return a<b},gte:function(a,b){return a>=b},lte:function(a,b){return a<=b},icontains:function(a,b){return-1<a.toLowerCase().indexOf(b.toLowerCase())},contains:function(a,b){return-1<a.indexOf(b)},"in":function(a,b){return-1<b.indexOf(a)},not_in:function(a,b){return-1===b.indexOf(a)}};e.prototype.__filter=function(a,b){this.__validate__();b=!!b;for(var d=0,c=a.length;d<
c;d++)if("object"!==typeof a[d]||null===a[d])a[d]={};a.length||(a=[{}]);var f=this._data.slice(),h,g,t,r,n,p,s=a.length,m;for(m=0;m!==s;m++){h=a[m];g=Object.keys(h);r=[];d=0;for(c=g.length;d<c;d++){t=g[d];n=t.split("__");2>n.length&&n.push("is");p=n.pop();n=n.join("__");if(!this.__compare[p])throw Error('Filter type "'+p+'" not supported.');r.push([this.__compare[p],n,h[t]])}a[m]=r}for(var q,c=f.length,l,k=0,u=Array(c),d=0;d!==c;d++)for(p=f[d],l=!0,h=0;h!==s&&l;h++){l=!1;r=a[h];m=r.length;for(g=0;g!==
m&&!l;g++)q=r[g],n=q[0],t=q[1],q=q[2],n(p[t],q)===b&&(l=!0);!l&&(u[k++]=p)}u=u.slice(0,k);return new e(this.__parent,u)};e.prototype.filter=function(a){var b=[].slice.call(arguments);return this.__filter(b,!1)};e.prototype.exclude=function(a){var b=[].slice.call(arguments);return this.__filter(b,!0)};e.prototype.spawn=function(a){this.__validate__();var b=new g(this._data);if(a)return b;this.__parent.__index&&b.defineIndex(this.__parent.__index);return b};e.prototype.each=function(a){if("function"!==
typeof a)throw Error("DataCollectionQuery.each expects a callback");for(var b=this._data,d=0,c=b.length;d<c;d++)a.call(this,b[d],d);return this};e.prototype.update=function(a){this.__validate__();for(var b=Object.keys(a),d,c=b.length,f=0;f<c;f++)d=b[f],b[f]=[d,a[d]];a=this._data;for(var f=0,h=a.length;f<h;f++)for(var e=a[f],g=0;g<c;g++)d=b[g],e[d[0]]=d[1];return this};e.prototype.remove=function(){this.__validate__();this.update({__remove__:!0});return this.__parent.__remove__(this.count())};e.prototype.sort=
function(a,b){this.__validate__();a=(a+"").replace(/[^A-Za-z0-9]/gi,"_");var d=new Function("a","b",["var val = "+(b?-1:1)+";","if(a['"+a+"'] === b['"+a+"']) { return a.__uniqid__ > b.__uniqid__ ? (val) : -(val); }","if(a['"+a+"'] === undefined) { return -(val); }","if(b['"+a+"'] === undefined) { return (val); }","if(a['"+a+"'] === null) { return -(val); }","if(b['"+a+"'] === null) { return (val); }","if(typeof a['"+a+"'] === 'number') {","  if(typeof b['"+a+"'] === 'number') {","    if(isNaN(a['"+
a+"']) && isNaN(b['"+a+"'])) { return a.__uniqid__ > b.__uniqid__ ? (val) : -(val); }","    if(isNaN(b['"+a+"'])) { return (val); }","    return a['"+a+"'] > b['"+a+"'] ? (val) : -(val);","  }\n  return -(val);\n}","if(typeof a['"+a+"'] === 'boolean') {","  if(typeof b['"+a+"'] === 'number') { return (val); }","  if(typeof b['"+a+"'] === 'boolean') { return a['"+a+"'] > b['"+a+"'] ? (val) : -(val); }","  return -(val);\n}","if(typeof a['"+a+"'] === 'string') {","  if(typeof b['"+a+"'] === 'string') { return a['"+
a+"'] > b['"+a+"'] ? (val) : -(val); }","  if(typeof b['"+a+"'] === 'object') { return -(val); }","  if(typeof b['"+a+"'] === 'function') { return -(val); }","  return (val);\n}","if(typeof a['"+a+"'] === 'object') {","  if(typeof b['"+a+"'] === 'object') { return a.__uniqid__ > b.__uniqid__ ? (val) : -(val); }","  if(typeof b['"+a+"'] === 'function') { return -(val); }","  return (val);\n}","if(typeof a['"+a+"'] === 'function') {","","  if(typeof b['"+a+"'] === 'function') { return a.__uniqid__ > b.__uniqid__ ? (val) : -(val); }",
"  return (val);\n}\nreturn a.__uniqid__ > b.__uniqid__ ? (val) : -(val);"].join("\n")),d=this._data.slice().sort(d);return new e(this.__parent,d)};e.prototype.values=function(a){this.__validate__();if(!a)return this._data.slice();for(var b=this._data,d=b.length,c=Array(d),f=0;f<d;f++)c[f]=b[f][a];return c};e.prototype.max=function(a){this.__validate__();var b=this._data,d=b.length,c=null,f;if(!d)return 0;for(var c=b[0][a],e=1;e<d;e++)f=b[e][a],f>c&&(c=f);return c};e.prototype.min=function(a){this.__validate__();
var b=this._data,d=b.length,c=null,f;if(!d)return 0;for(var c=b[0][a],e=1;e<d;e++)f=b[e][a],f<c&&(c=f);return c};e.prototype.sum=function(a){this.__validate__();var b=this._data,d=b.length,c;if(!d)return 0;c=parseFloat(b[0][a]);for(var f=1;f<d&&!isNaN(c);f++)c+=parseFloat(b[f][a]);return c};e.prototype.avg=function(a){this.__validate__();var b=this._data,d=b.length,c;if(!d)return 0;c=parseFloat(b[0][a]);for(var f=1;f<d&&!isNaN(c);f++)c+=parseFloat(b[f][a]);return c/d};e.prototype.reduce=function(a,
b){this.__validate__();var d=this._data,c=d.length,f,e;if(!c)return null;e=d[0][a];for(var g=1;g<c;g++)f=d[g][a],e=b.call(this,e,f,g);return e};e.prototype.distinct=function(a){this.__validate__();var b=this._data,d=b.length,c=Object.create(null),f;if(d){c[b[0][a]]=!0;for(var e=1;e<d;e++)f=b[e][a],c[f]||(c[f]=!0)}return Object.keys(c)};e.prototype.sequence=function(a){this.__validate__();var b=this.__parent;if(!b.__index)throw Error("Can only use .sequence with an indexed DataCollection");a instanceof
Array||(a=[].slice.call(arguments));for(var d=[],c=b.__indexedRows,f=0,g=a.length;f<g;f++)b=a[f],c[b]&&d.push(c[b]);return new e(this.__parent,d)};e.prototype.limit=function(a,b){this.__validate__();"undefined"===typeof b&&(b=a,a=0);return new e(this.__parent,this._data.slice(a,a+b))};e.prototype.count=function(){this.__validate__();return this._data.length};e.prototype.first=function(){return this._data.length?this._data[0]:null};e.prototype.last=function(){return this._data.length?this._data[this._data.length-
1]:null};v.DataCollection=g}(window);
